apiVersion: apps/v1 
kind: Deployment
metadata:
  name: node-deployment
  namespace: tokenization
  labels:
    app.nodejs: api-nodejs
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.nodejs: api-nodejs
  template:
    metadata:
      labels:
        app.nodejs: api-nodejs
    spec:
      containers:
      - name: node
        image: 326549183442.dkr.ecr.eu-west-1.amazonaws.com/tokenization-repo:10.0.6
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
          - containerPort: 2000
        env:
          - name: REDIS_SERVER
            value: redis
          - name: REDIS_USER
            value: default
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password
          - name: HOST_MYSQL
            value: mysql-service
          - name: USER_MYSQL
            value: root
          - name: PASS_MYSQL
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password

        