apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: tokenization
spec:
  selector:
    app.nodejs: api-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2000
  type: LoadBalancer  
  