apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pvv
  namespace: tokenization
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: "/var/lib/mysql"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual